# Generated by Django 5.0.3 on 2024-04-16 17:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
